# ==========================================
# CONFIGURAÇÕES GERAIS DA APLICAÇÃO
# ==========================================
spring.application.name=nutriconecta

# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS (MySQL)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
# Atualiza a estrutura do banco automaticamente se houver mudanças nas suas classes Java (Entidades)
spring.jpa.hibernate.ddl-auto=update

# Mostra no console (log) os comandos SQL que o Hibernate está executando por baixo dos panos
spring.jpa.show-sql=true

# CORREÇÃO: O dialeto foi atualizado para a versão genérica suportada pelas versões mais recentes do Spring Boot.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect